version: '2.2'
services:
  frontend:
    build: ui/.
    depends_on:
      - backend
    ports:
      - 5000:5000
  backend:
    build: .
    environment:
      DATABASE_URL: postgresql://registry-watcher:registry-watcher@db/registry-watcher?sslmode=disable
      VAULT_TOKEN: ${VAULT_TOKEN}
      NOMAD_TOKEN: ${NOMAD_TOKEN}
    volumes:
      - ${PWD}/config:/app/config
    ports:
      - 8080:8080
  db:
    image: postgres:9.6.2
    environment:
      POSTGRES_USER: registry-watcher
      POSTGRES_DB: registry-watcher
      POSTGRES_PASSWORD: registry-watcher
    ports:
      - 5432:5432
