version: '3'
services:
  ui:
    build: ../../ui/.
    depends_on:
      - app
    ports:
      - 5000:5000
  
  app:
    container_name: dev
    build:
      context: ../../
      dockerfile: env/dev/Dockerfile
    ports:
      - 8080:8080
    environment:
      - ENV=dev
    depends_on:
      - db

  db:
    container_name: dev-db
    image: postgres:16.2-alpine
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=abcdefg
      - POSTGRES_DB=playground