version: '3.8'
services:
  backend:
    image: mcr.microsoft.com/devcontainers/go:0-1.17-bullseye
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity
    environment:
      DATABASE_URL: postgresql://registry-watcher:registry-watcher@db/registry-watcher?sslmode=disable
      VAULT_TOKEN: ${VAULT_TOKEN}
      NOMAD_TOKEN: ${NOMAD_TOKEN}

  db:
    image: postgres:9.6-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: registry-watcher
      POSTGRES_DB: registry-watcher
      POSTGRES_PASSWORD: registry-watcher

volumes:
  postgres-data: