name: PR Size Labeler
on: pull_request
permissions:
  # All other permissions are set to none
  # Adding permissions are needed to allow dependabot PRs to use size labeler
  checks: write
  contents: read
  pull-requests: write

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.1.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
